import constants

SCALE = 3
SCREEN_WIDTH = constants.ORIGINAL_WIDTH * SCALE
SCREEN_HEIGHT = constants.ORIGINAL_HEIGHT * SCALE

# Gameplay settings
ALIEN_ROWS = 3
ALIEN_COLUMNS = 6
ALIEN_SPACING_X = 40
ALIEN_SPACING_Y = 30
ALIEN_MARGIN_X = 20
ALIEN_MARGIN_Y = 40
BULLET_SPEED = -7
BOMB_SPEED = 4
UFO_INTERVAL = 25000  # milliseconds
